modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/auto_crouch/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "auto_crouch"
version = "${version}"
displayName = "Auto Crouch"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.auto_crouch]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.auto_crouch]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.auto_crouch]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
